# file: .pre-commit-config.yaml
#
repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
    - id: requirements-txt-fixer
    - id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
    - id: isort
